import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import abd from "../public/abd2.png";
import net from "../public/net.png";
import todo from "../public/todo.png";
import nvidia from "../public/nvidia.png";
import amazon from "../public/amazon.png";
import foot from "../public/ast.png";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const [DarkMode, setDarkMode] = useState(true);
  return (
    <div className={DarkMode ? "dark" : ""}>
      <Head>
        <title>Akash Boby Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white  dark:bg-gray-900 ">
        <section className=" min-h-min">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-burtons m-10 mt-8 dark:text-lime-500">
              Akash Boby dB
            </h1>
            <ul className=" flex items-center">
              <li className=" cursor-pointer text-xl">
                <BsFillMoonStarsFill
                  onClick={() => {
                    setDarkMode(!DarkMode);
                  }}
                />
              </li>
              <li className="   bg-gradient-to-r from-red-800 to-amber-300 py-2 px-4 text-white rounded-md ml-8 max-w-screen-md  mr-5">
                <Link href="">Resume</Link>
              </li>
            </ul>
          </nav>
          <div className=" text-center px-20">
            <h1 className=" text-4xl py-2 text-cyan-400 font-burtons md:text-6xl">
              Akash B
            </h1>
            <h3 className=" text-2xl py-2 md:3xl dark:text-white">
              Web Developer
            </h3>
            <p className=" text-md py-2 leading-8 text-gray-700 md:xl mx-w-s dark:text-white">
              To be part of an organization, which will allow me to learn,
              develop, innovate and utilize the skills to contribute towards the
              success and growth of the company through my key strengths and
              unique abilities, thereby excel and direct my career to the
              pinnacle through the concerned organization and industry.
            </p>
          </div>
          <div className=" text-5xl flex  justify-center gap-10 text-sky-600 cursor-pointer">
            <Link href="https://www.linkedin.com/in/akashbobydb">
              <AiFillLinkedin />
            </Link>
            <Link href="https://www.github.com/akashbobydb">
              <AiFillGithub />
            </Link>
          </div>
          <div className=" relative mx-auto bg-gradient-to-b from-green-300  to-yellow-400 rounded-full w-80 h-80 mt-20  overflow-hidden">
            <Image layout="fill" objectFit="cover" src={abd} />
          </div>
        </section>
        <section>
          <div className=" mx-auto mt-20  bg-gradient-to-b from-slate-50 to-amber-400 rounded-lg max-w-md box-border shadow-lg ">
            <h1 className=" text-center  text-zinc-900 text-lg font-bold  font-sans ">
              SKILLS
            </h1>
            <p className=" text-center text-gray-600 dark:text-gray-900">
              ReactJs
            </p>
            <p className=" text-center text-gray-600 dark:text-gray-900">
              Tailwind Css
            </p>
            <p className=" text-center text-gray-600 dark:text-gray-900">
              Javascript
            </p>
            <p className=" text-center text-gray-600 dark:text-gray-900">
              NextJs
            </p>
            <p className=" text-center text-gray-600 dark:text-gray-900">
              HTML5
            </p>
            <p className=" text-center text-gray-600 dark:text-gray-900">CSS</p>
            <p className=" text-center text-gray-600 dark:text-gray-900">
              Bootstrap
            </p>
          </div>
        </section>
        <section className=" my-10">
          <div>
            <h1 className=" text-3xl py-2 ml-20 dark:text-white">
              My Projects:
            </h1>
          </div>
          <div className="lg:flex gap-10">
            <div className=" text-center shadow-lg p-10 rounded-xl ml-10">
              <Image src={amazon} width={100} height={100} alt="nvidia" />
              <h1 className=" py-2 text-lg font-medium pt-8 pb-2 dark:text-white">
                Amazon
              </h1>
              <p className="py-3 dark:text-slate-50">
              Amazon.com is a vast Internet-based enterprise that sells books, music, movies, housewares, electronics, toys, and many other goods, either directly or as the middleman between other retailers and Amazon.com's millions of customers.
              </p>
              <h4 className="py-4  text-sky-500 dark:text-amber-400">
                Tools I use:
              </h4>
              <p className=" text-gray-600 py-1 dark:text-slate-100">ReactJS</p>
              <p className=" text-gray-600 py-1 dark:text-slate-100">HTML5</p>
              <p className=" text-gray-600 py-1 dark:text-slate-100">
                Bootstrap
              </p>
              <p className=" text-gray-600 py-1 dark:text-slate-100">
                Tailwind Css
              </p>
              <Link href="https://amazon-using-react.vercel.app/">
                <h1 className=" cursor-pointer font-serif font-semibold text-black dark:text-slate-100">
                  Click Here To Visit
                </h1>
              </Link>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl ml-10 dark:text-slate-50">
              <Image src={todo} width={100} height={100} alt="todo" />
              <h1 className=" py-2 text-lg font-medium pt-8 pb-2 text-center">
                To-Do
              </h1>
              <p className="py-3 text-center ">
                it is a list of tasks you need to complete or things that you
                want to do. Most typically, they are organised in order of
                priority.
              </p>
              <h4 className="py-4  text-sky-500 dark:text-amber-400 text-center">
                Tools I use:
              </h4>
              <p className=" py-1 text-gray-600 dark:text-slate-100 text-center">
                ReactJS
              </p>
              <p className=" py-1 text-gray-600 dark:text-slate-100 text-center">
                HTML5
              </p>
              <p className=" py-1 text-gray-600 dark:text-slate-100 text-center">
                Bootstrap
              </p>
              <Link href="https://todo-using-react.vercel.app/">
                <h1 className=" cursor-pointer font-serif font-semibold text-black dark:text-slate-100">
                  Click Here To Visit
                </h1>
              </Link>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl ml-10">
              <Image src={net} width={100} height={100} alt="netflix" />
              <h1 className=" py-2 text-lg font-medium pt-8 pb-2 dark:text-white text-center">
                Netflix
              </h1>
              <p className="py-3 dark:text-slate-50 text-center">
                A huge selection of movies and TV shows old and new, tons of
                high-quality original programs, and an easy-to-navigate
                interface.
              </p>
              <h4 className="py-4  text-sky-500 dark:text-amber-400 text-center">
                Tools I use:
              </h4>
              <p className=" py-1 text-gray-600 dark:text-slate-100 text-center">
                ReactJS
              </p>
              <p className=" py-1 text-gray-600 dark:text-slate-100 text-center">
                HTML5
              </p>
              <p className=" py-1 text-gray-600 dark:text-slate-100 text-center">
                Bootstrap
              </p>
              <Link href="https://netfliix-using-react.vercel.app/">
                <h1 className=" cursor-pointer font-serif font-semibold text-black dark:text-slate-100">
                  Click Here To Visit
                </h1>
              </Link>
            </div>
            <div className=" text-center shadow-lg p-10 rounded-xl ml-10">
              <Image src={nvidia} width={100} height={100} alt="netflix" />
              <h1 className=" py-2 text-lg font-medium pt-8 pb-2 dark:text-white text-center">
                Nvidia
              </h1>
              <p className="py-3 dark:text-slate-50 text-center">
                Developing integrated circuits, which are used in everything
                from electronic game consoles to personal computers.
              </p>
              <h4 className="py-4  text-sky-500 dark:text-amber-400 text-center">
                Tools I use:
              </h4>
              <p className=" py-1 text-gray-600 dark:text-slate-100 text-center">
                ReactJS
              </p>
              <p className=" py-1 text-gray-600 dark:text-slate-100 text-center">
                HTML5
              </p>
              <p className=" py-1 text-gray-600 dark:text-slate-100 text-center">
                Bootstrap
              </p>
              <p className=" py-1 text-gray-600 dark:text-slate-100 text-center">
                Tailwind Css
              </p>
              <Link href="https://amazon-using-react.vercel.app/">
                <h1 className=" cursor-pointer font-serif font-semibold text-black dark:text-slate-100">
                  Click Here To Visit
                </h1>
              </Link>
            </div>
          </div>
        </section>
      </main>
      <div class="max-h-15 -mt-10 bg-gradient-to-r from-violet-500 to-fuchsia-500">
        <footer>
          <h1 className=" py-2 ml-4 pb-2 ">Email: akashdinakumar@gmail.com</h1>
          <h3 className=" py-0 ml-4">All Right Reserved.</h3>
        </footer>
      </div>
    </div>
  );
}
